Rcrontab_web/urls.py
from django.contrib import admin
from django.urls import path, include
from rcrontab import views
from crontab_formal.views import send_email

urlpatterns = [
    path('admin/', admin.site.urls),
    path('index/', include('rcrontab.urls')),
    path('logout/', views.do_logout),
    path('crontab/', include('crontab_formal.urls')),
    path('accounts/login/', views.do_login),
    path('send_mail/', send_email)
]

rcrontab/urls.py
from django.urls import path, re_path
from rcrontab import views

app_name = 'index'
urlpatterns = [
    re_path('(?P<mode>[a-zA-z0-9]+)/(?P<sid>[0-9]+)/', views.index, name='index_mode_sid'),
    re_path('(?P<mode>[a-zA-z0-9]+)/', views.index, name='index_mode'),
    path('', views.index),

]

crontab_formal/models.py
from django.db import models
# Create your models here.


class ServerInfo(models.Model):
    is_alive = ((1, 'on_line'), (0, 'off_line'))
    ip = models.GenericIPAddressField(protocol='IPv4')
    port = models.IntegerField(default=33541)
    name = models.CharField(max_length=100)
    uptime = models.DateTimeField(auto_now=True)
    status = models.IntegerField(choices=is_alive, default=0)

    def __str__(self):
        return 'IP:%s, is_alive:%s' % (self.ip, self.status)

    class Meta:
        db_table = 'py_script_server_info_v2'


class Path(models.Model):
    server = models.ForeignKey('ServerInfo', on_delete=models.DO_NOTHING)
    path = models.CharField(max_length=200)
    project = models.CharField(verbose_name='项目名称', max_length=50)

    def __str__(self):
        return "project:(%s),[Server:(%s)]Path:%s" % (self.project, self.server, self.path)

    class Meta:
        db_table = 'py_script_programs_path'
        unique_together = ('server', 'path', 'project')


class ConfigFileLog(models.Model):
    path = models.ForeignKey('Path', on_delete=models.DO_NOTHING)
    project_conf = models.FileField(upload_to='project_conf/', unique=True)
    project_package = models.FileField(upload_to='project_package/', blank=True, null=True)
    comments = models.TextField(blank=True, null=True)

    class Meta:
        db_table = 'py_script_config_file_log'


class TablesInfo(models.Model):
    db = (('db_ali', 'db_阿里云'), ('db_151', 'db_151'), ('db_153', 'db_153'))
    db_server = models.CharField(max_length=20, choices=db)
    db_name = models.CharField(max_length=30)
    table_name = models.CharField(max_length=100)

    def __str__(self):
        return "%s:%s.%s" % (self.db_server, self.db_name, self.table_name)

    class Meta:
        db_table = 'py_script_tables_info'
        unique_together = ('db_server', 'db_name', 'table_name')


class PyScriptBaseInfoV2(models.Model):
    exec_plan_choice = ((1, 'day'),
                        (2, 'month'),
                        (3, 'quarter'))

    is_stop_choice = ((0, '执行'),
                      (1, '停止'))

    is_test = ((1, '测试'), (0, '正式'),)

    run_type = ((0, '调用api'),
                (1, '调用程序'))

    program_type = ((0, '抓取'),
                    (1, '计算'),
                    (2, '其他'))

    sid = models.AutoField(primary_key=True)
    name = models.CharField(verbose_name='名称', max_length=500)
    program_type = models.IntegerField(verbose_name='程序类型', choices=program_type)
    version = models.DateField(blank=True, null=True)
    run_type = models.SmallIntegerField(choices=run_type, default=0)
    pre_tables = models.ManyToManyField('TablesInfo', related_name='son_program', blank=True )
    result_tables = models.ManyToManyField('TablesInfo', related_name='father_program')
    path = models.ForeignKey('Path', on_delete=models.CASCADE, related_name='program')
    function = models.TextField(verbose_name='程序功能', max_length=50)
    exec_plan = models.IntegerField(verbose_name='执行计划', choices=exec_plan_choice)
    exec_month = models.CharField(max_length=30, blank=True, null=True)
    exec_day = models.CharField(max_length=30, blank=True, null=True)
    exec_time = models.CharField(max_length=50, blank=True, null=True)
    owner = models.ForeignKey('PyScriptOwnerListV2', on_delete=models.CASCADE, related_name='programs')
    times = models.IntegerField(default=1)
    is_stop = models.IntegerField(default=0, choices=is_stop_choice)
    is_test = models.IntegerField(default=0, choices=is_test)

    def __str__(self):
        return "sid:%s server:%s script_name:%s " % (self.sid, self.path, self.name)

    class Meta:
        db_table = 'py_script_base_info_v2'


class PyScriptOwnerListV2(models.Model):
    owner = models.CharField(verbose_name='所有者', max_length=10, primary_key=True)
    mail = models.EmailField()

    def __str__(self):
        return self.owner

    class Meta:
        db_table = 'py_script_owners_info_v2'


class ResultLog(models.Model):
    event_type_list = ((0, '执行调度'), (1, '开始执行'), (2, '正常结束'), (3, '异常终止'),
                       (4, '质控正常'), (5, '质控异常'))
    script = models.ForeignKey('PyScriptBaseInfoV2', on_delete=models.CASCADE,
                               related_name='result', db_column='sid', null=True)
    version = models.DateField()
    event_time = models.DateTimeField()
    subversion = models.DateTimeField(blank=True, null=True)
    event_type = models.IntegerField(choices=event_type_list)
    extra_info = models.TextField(blank=True, null=True)
    flag = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.script, self.version

    class Meta:
        db_table = 'py_script_result_log'

templates/rcrontab_formals/get_plan.html
{% extends 'Base.html' %}

{% block container %}

    <div class="bs-example bs-example-tabs" data-example-id="togglable-tabs">
    <ul id="myTabs" class="nav nav-pills" role="tablist">
        {% for owner in programs_dict %}
            {% if forloop.counter == 1 %}
            <li role="presentation" class="active"><a href="#{{ owner }}" id="{{ owner }}-tab" role="tab" data-toggle="tab" aria-controls="{{ owner }}" aria-expanded="true">{{ owner }}</a></li>
            {% else %}
            <li role="presentation" class=""><a href="#{{ owner }}" role="tab" id="{{ owner }}-tab" data-toggle="tab" aria-controls="{{ owner }}" aria-expanded="false">{{ owner }}</a></li>
            {% endif %}

        {% endfor %}
    </ul>

    <div id="myTabContent" class="tab-content">
        {% for owner_name,programs in programs_dict.items %}
            {% if forloop.counter == 1 %}
      <div role="tabpanel" class="tab-pane fade active in" id="{{ owner_name }}" aria-labelledby="{{ owner_name }}-tab">
            {% else %}
      <div role="tabpanel" class="tab-pane fade in" id="{{ owner_name }}" aria-labelledby="{{ owner_name }}-tab">
            {% endif %}
      <table class="table table-hover">
      <thead>
        <tr>
          <th>NO.</th>
          <th>program_name</th>
          <th>program_type</th>
          <th>program_version</th>
          <th>调用方式</th>
          <th>pre_tables</th>
          <th>result_tables</th>
          <th>program_function</th>
          <th>执行计划</th>
          <th>rerun_times</th>
        </tr>
      </thead>
      <tbody>
      {% for sid,program_info in  programs.items %}
          {% if program_info.program_info.is_stop == 1 %}
            <tr class="danger">
          {% elif program_info.program_info.is_test == 1 %}
            <tr class="warning">
          {% else %}
              <tr>
          {% endif %}
           <td>{{ program_info.program_info.sid }}</td>
          <td>{{ program_info.program_info.name|wordwrap:5 }}</td>
          <td>{% if program_info.program_info.program_type == 0 %}
                抓取程序
              {% elif program_info.program_info.exec_plan == 1%}
              计算程序
                {% else %}
              其他
              {% endif %}

          </td>
          <td>{{ program_info.program_info.version }}</td>
          <td>{% if program_info.program_info.run_type == 0%}
                调用url_api
              {% else %}
                调用程序
              {% endif %}
          </td>
          <td>{{ program_info.pre_tables |safe}}</td>
          <td>{{ program_info.result_tables |safe }}</td>
          <td>{{ program_info.program_info.function }}</td>
          <td>{% if program_info.program_info.exec_plan == 1 %}
              执行计划:每天<br>
              {% elif program_info.program_info.exec_plan == 2%}
              执行计划:每月<br>
              {% else %}
              执行计划:其他<br>
              {% endif %}
              time:{{ program_info.program_info.exec_time }}<br>
              (month:{{ program_info.program_info.exec_month }}/day:{{ program_info.program_info.exec_day }})</td>
          <td>{{ program_info.program_info.times }}</td>
          </tr>
       {% endfor %}
      </tbody>
    </table>
      </div>

        {% endfor %}

    </div>
  </div>
</div>

{% endblock %}

templates/rcrontab_formals/get_result.html
{% extends 'Base.html' %}

{% block container %}

    <div class="bs-example bs-example-tabs" data-example-id="togglable-tabs">
     <div class="panel-body">
    <ul id="owner_list" class="nav nav-pills" role="tablist">
        {% for owner in owners_list %}
            {% if forloop.counter == 1 %}
            <li role="presentation" class="active"><a id="{{ owner }}-tab" role="tab" data-toggle="tab" aria-controls="{{ owner }}" aria-expanded="true" onclick="submit(this)">{{ owner }}</a></li>
            {% else %}
            <li role="presentation" class=""><a  role="tab" id="{{ owner }}-tab" data-toggle="tab" aria-controls="{{ owner }}" aria-expanded="false" onclick="submit(this)">{{ owner }}</a></li>
            {% endif %}
        {% endfor %}
    </ul>
     </div>
    <div class="panel-body">
     <ul id="version_list" class="nav nav-pills" role="tablist">
        {% for version in version_list %}
            {% if forloop.counter == 1 %}
            <li role="presentation" class="active"><a id="{{ version }}-tab" role="tab" data-toggle="tab" aria-controls="{{ version }}" aria-expanded="true" onclick="submit(this)">{{ version }}</a></li>
            {% else %}
            <li role="presentation" class=""><a role="tab" id="{{ version }}-tab" data-toggle="tab" aria-controls="{{ version }}" aria-expanded="false" onclick="submit(this)">{{ version }}</a></li>
            {% endif %}
        {% endfor %}
    </ul>
    </div>
    </div>

    <div id="myTabContent" class="tab-content">


  </div>
    <script src="/static/jquery-3.2.1.js"></script>
    <script>
    function submit(ths) {
        var parent = $(ths).parent().parent().attr('id')
        if(parent=='owner_list'){
            var Owner=$(ths).text()
            var version=$('#version_list').children('.active').text()
        }else {
            var Owner=$('#owner_list').children('.active').text()
            var version=$(ths).text()
        }
        var data={'owner': Owner, 'version':version}
        get_result(data)
    };

    function get_result(data) {
        $.ajax({
                type:"get",
                url:"{{ request.path }}",
                data:data,
                success: function (arg) {
                    $("#myTabContent").empty()
                    $('#myTabContent').append(arg)
                }
            });
    }

    $(function(){
function load_data() {
    var version = $('#version_list').children('.active').text()
    var Owner = $('#owner_list').children('.active').text()
    var data = {'owner': Owner, 'version': version}
    console.log(data)
    get_result(data)
}
load_data();
setInterval(load_data,30000);// 注意函数名没有引号和括弧！
// 使用setInterval("show()",3000);会报“缺少对象”

});



    </script>
{% endblock %}


        window.onload = function () {
        var version=$('#version_list').children('.active').text()
        var Owner=$('#owner_list').children('.active').text()
        var data={'owner': Owner, 'version':version}
        console.log(data)
        get_result(data)

    };

templates/rcrontab_formals/get_result_table.html
<table class="table table-hover">
      <thead>
        <tr>
          <th>sid</th>
          <th>version</th>
          <th>owner</th>
          <th>begin_time</th>
          <th>exec_result</th>
          <th>end_time</th>
          <th>extra_info</th>
          <th>result_table_id</th>
          <th>exec_plan</th>
        </tr>
      </thead>
      <tbody>
      {% for result_info in  result_list %}
          <tr>
          <th>{{ result_info.0|cut:"None" }}
              {% if result_info.10 > 0 %}
           <span class="badge">{{ result_info.10}}</span>
              {% endif %}
          </th>
          <td>{{ result_info.2|date:"Y-m-d"|cut:"None" }}</td>
          <td>{{ result_info.3|cut:"None"|wordwrap:10 }}</td>
          <td>{{ result_info.4|cut:"None" }}</td>
              {% if result_info.11 == 1 %}
                  <td style="color: orangered">
                  正在重跑
              {% elif result_info.5 == 3 %}
                  <td style="color: red">
                  异常
              {% elif result_info.5 == 2 %}
                  <td style="color: green">
                  正常
              {% elif result_info.11 == 2 %}
                  <td style="color: orange">
                  正在执行
              {% else %}
                  <td>
              {% endif %}
                </td>
          <td>{{ result_info.6|cut:"None" }}</td>
          <td>{{ result_info.7|truncatechars:50|cut:"None" }}</td>
          <td>{{ result_info.8|cut:"None" }}</td>
          <td>
              {% if result_info.9 == 1 %}
                  每天
              {% elif result_info.9 == 2%}
                  每月
               {% else %}
                    其他
                {% endif %}
          </td>
          </tr>
       {% endfor %}
      </tbody>
    </table>

templates/rcrontab_formals/insert.html
{% extends 'Base.html' %}

{% block container %}


     <form  enctype="multipart/form-data" method="post" name="plan_info" id="insert_plan">
			<div class="modal-body">{% csrf_token %}

<table class="table">
    <thead>
    <tr>
        <th>字段</th>
        <th>值</th>
    </tr>
    </thead>
    <tbody>
    {% for item in form %}
        <tr>
        <td>{{ item.label_tag }}</td>
        <td>{{ item }}</td>
        </tr>
    {% endfor %}
    </tbody>
</table>
{% if errs %}
<div class="alert alert-danger alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        {{ errs }}
</div>
{% endif %}
			</div>
			<div class="modal-footer">
			</div>
            </form>
                <button type="button" class="btn btn-primary" onclick="submit_data()" data-toggle="modal" data-target="#myModal">
					提交
				</button>


    <!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">提交执行计划</h4>
      </div>
      <div class="modal-body">
        <div class="progress">
        <div class="progress-bar progress-bar-striped active" role="progressbar" aria-valuenow="45" aria-valuemin="0" aria-valuemax="100" style="width: 0%"><span class="sr-only">0%</span>
        </div>
        </div>
          <div id="in_modal">

          </div>
      </div>
    </div>
  </div>
</div>

{% endblock %}

{% block script %}
    <script>
function onprogress(evt){
　　var loaded = evt.loaded;     //已经上传大小情况
 var tot = evt.total;      //附件总大小
 var per = Math.floor(100*loaded/tot);  //已经上传的百分比
　　$(".progress-bar").css('width',per+"%")
    $(".progress-bar").text(per)

}

function submit_data() {
    var form_data = new FormData();
    form_data.append('path', $('#id_path').val());
    form_data.append('project_conf', $('#id_project_conf')[0].files[0]);
    form_data.append('project_package', $('#id_project_package')[0].files[0]);
    form_data.append('comments', $('#id_comments').val());
    $(".progress-bar").css('width',"0%")
    $(".progress-bar").text(0)
            $.ajax({
                type:"post",
                url: "{{ request.path }}",
                data: form_data,
                contentType:false,
                processData:false,

                //这里我们先拿到jQuery产生的 XMLHttpRequest对象，为其增加 progress 事件绑定
                xhr: function(){
　　　　　　    var xhr = $.ajaxSettings.xhr();
　　　　　　    if(onprogress && xhr.upload) {
　　　　　　　　xhr.upload.addEventListener("progress" , onprogress, false);
　　　　　　　　return xhr;}
　　　　        },
                success:function (arg) {
                    $("#in_modal").empty()
                    $("#in_modal").append(arg)
            }
    });
}


</script>
{% endblock %}

templates/rcrontab_formals/test.html
<div class="bs-example bs-example-tabs" data-example-id="togglable-tabs">
    <ul id="myTabs" class="nav nav-tabs" role="tablist">
      <li role="presentation" class="active"><a href="#home" id="home-tab" role="tab" data-toggle="tab" aria-controls="home" aria-expanded="true">Home</a></li>
      <li role="presentation" class=""><a href="#profile" role="tab" id="profile-tab" data-toggle="tab" aria-controls="profile" aria-expanded="false">Profile</a></li>
      <li role="presentation" class="dropdown">
        <a href="#" id="myTabDrop1" class="dropdown-toggle" data-toggle="dropdown" aria-controls="myTabDrop1-contents" aria-expanded="false">Dropdown <span class="caret"></span></a>
        <ul class="dropdown-menu" aria-labelledby="myTabDrop1" id="myTabDrop1-contents">
          <li class=""><a href="#dropdown1" role="tab" id="dropdown1-tab" data-toggle="tab" aria-controls="dropdown1" aria-expanded="false">@fat</a></li>
          <li class=""><a href="#dropdown2" role="tab" id="dropdown2-tab" data-toggle="tab" aria-controls="dropdown2" aria-expanded="false">@mdo</a></li>
        </ul>
      </li>
    </ul>
    <div id="myTabContent" class="tab-content">
      <div role="tabpanel" class="tab-pane fade active in" id="home" aria-labelledby="home-tab">
        <p>Raw denim you probably haven't heard of them jean shorts Austin. Nesciunt tofu stumptown aliqua, retro synth master cleanse. Mustache cliche tempor, williamsburg carles vegan helvetica. Reprehenderit butcher retro keffiyeh dreamcatcher synth. Cosby sweater eu banh mi, qui irure terry richardson ex squid. Aliquip placeat salvia cillum iphone. Seitan aliquip quis cardigan american apparel, butcher voluptate nisi qui.</p>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="profile" aria-labelledby="profile-tab">
        <p>Food truck fixie locavore, accusamus mcsweeney's marfa nulla single-origin coffee squid. Exercitation +1 labore velit, blog sartorial PBR leggings next level wes anderson artisan four loko farm-to-table craft beer twee. Qui photo booth letterpress, commodo enim craft beer mlkshk aliquip jean shorts ullamco ad vinyl cillum PBR. Homo nostrud organic, assumenda labore aesthetic magna delectus mollit. Keytar helvetica VHS salvia yr, vero magna velit sapiente labore stumptown. Vegan fanny pack odio cillum wes anderson 8-bit, sustainable jean shorts beard ut DIY ethical culpa terry richardson biodiesel. Art party scenester stumptown, tumblr butcher vero sint qui sapiente accusamus tattooed echo park.</p>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="dropdown1" aria-labelledby="dropdown1-tab">
        <p>Etsy mixtape wayfarers, ethical wes anderson tofu before they sold out mcsweeney's organic lomo retro fanny pack lo-fi farm-to-table readymade. Messenger bag gentrify pitchfork tattooed craft beer, iphone skateboard locavore carles etsy salvia banksy hoodie helvetica. DIY synth PBR banksy irony. Leggings gentrify squid 8-bit cred pitchfork. Williamsburg banh mi whatever gluten-free, carles pitchfork biodiesel fixie etsy retro mlkshk vice blog. Scenester cred you probably haven't heard of them, vinyl craft beer blog stumptown. Pitchfork sustainable tofu synth chambray yr.</p>
      </div>
      <div role="tabpanel" class="tab-pane fade" id="dropdown2" aria-labelledby="dropdown2-tab">
        <p>Trust fund seitan letterpress, keytar raw denim keffiyeh etsy art party before they sold out master cleanse gluten-free squid scenester freegan cosby sweater. Fanny pack portland seitan DIY, art party locavore wolf cliche high life echo park Austin. Cred vinyl keffiyeh DIY salvia PBR, banh mi before they sold out farm-to-table VHS viral locavore cosby sweater. Lomo wolf viral, mustache readymade thundercats keffiyeh craft beer marfa ethical. Wolf salvia freegan, sartorial keffiyeh echo park vegan.</p>
      </div>
    </div>
  </div>